### ISSUE TITLE
Support for PHP?

### ISSUE THREAD

**Issue by Ace-COM** [philippefichet/sonarlint4netbeans#10]
Hello Philippe,

would it be possible to add PHP support for this plugin? I mainly use PHP / JS (node.js) for my work, so PHP support would be highly appreciated.

Less important, but also a nice one would be support for CSS/LESS/SASS, but these are not so important

**Comment by philippefichet** [comment]
Hello,

Thank you for this issue.

I can add PHP, but no CSS/LESS/SASS because no present on https://github.com/SonarSource/sonarlint-core/blob/master/core/src/main/java/org/sonarsource/sonarlint/core/client/api/common/Language.java to enable it.

I will try to add PHP support soon ;)

**Comment by Ace-COM** [comment]
Thank you very much... I use your plugin, for JS and PHP would help too. I am looking forward for the update :)

**Comment by philippefichet** [comment]
Support for PHP added in version 2.4.0 ;)
