### ISSUE TITLE
Red underline is irritating

### ISSUE THREAD

**Issue by jiai** [philippefichet/sonarlint4netbeans#3]
It would be nice if the color of the underline would be a color other than red, even if the severity is major or critical. With red I associate a syntax error that prevents compilation.

**Comment by philippefichet** [comment]
Hello,
You can change the style of each "Annotations" (in the Netbeans sense) in "Options" > "Fonts & Colors" > "Annotations".
![SonarLintAnnotationStyleConfiguration](https://user-images.githubusercontent.com/6843043/89549521-b1a5ea00-d808-11ea-82c0-a5e5ea537bee.png)

**Comment by jiai** [comment]
Unfortunately, no sonarlLint annotations are displayed after a color change. I got the Exception "IllegalStateException: Annotation not added: com-github-philippefichet-sonarlint4netbeans-annotation-minorjava:S1128 Unnecessary imports should be removed Click to show details". This was only the first sonarLint annotation.

**Comment by jiai** [comment]
Forget about it - after two restarts and a long waiting time, the annotions appeared in the selected colors. :-)

**Comment by philippefichet** [comment]
Nice :)
