### ISSUE TITLE
Stylesheet for Sonar Rule Details Window is missing

### ISSUE THREAD

**Issue by jiai** [philippefichet/sonarlint4netbeans#4]
For the  Sonar Rule Details Window a style sheet would be very nice. At the moment the output looks a bit like the WWW of 1996.

**Comment by philippefichet** [comment]
Can you try this [pre-release](https://github.com/philippefichet/sonarlint4netbeans/releases/tag/pre-release%2Fcustomize-sonar-rule-derails) and tell me if it's okay with you ?

**Comment by jiai** [comment]
Hi Philippe,
I don't see any sonarlint badges at all. :-(

Greetings,
Jessica

**Comment by philippefichet** [comment]
I am not sure, do you mean the annotations to the left of the editor?

**Comment by jiai** [comment]
Yes

**Comment by jiai** [comment]
Due to a miracle, the annotations are here now. :)

**Comment by philippefichet** [comment]
Nice :)
I plan to add an icon to know its status but I'm running out of time.

**Comment by jiai** [comment]
Hi Philippe,

 

a first try:

 


/**

  Style for SonarLint Details window rule

  See javax.swing.text.html.CSS for more available attributes

*/

body {

     font-family: sans-serif;

     color:#333333;

padding-left: 5px;

padding-right: 5px;

}

 

h1 {

     font-size: large;

}

 

a {

     text-decoration: none;

     color:#003399

}

 

h2 {

     font-size: medium;

}

 

pre {

     color: #222222;

     background-color: #efefef;

     width: 75%;

     margin: 5px;

     padding:5px;

}


 

Thank you very much for this tool! :-)

 

Greetings,

Jessica

 
 

Gesendet: Montag, 28. September 2020 um 17:50 Uhr
Von: "FICHET Philippe" <notifications@github.com>
An: "philippefichet/sonarlint4netbeans" <sonarlint4netbeans@noreply.github.com>
Cc: "jiai" <jessica-aileen@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [philippefichet/sonarlint4netbeans] Stylesheet for Sonar Rule Details Window is missing (#4)


 

Nice :)
I plan to add an icon to know its status but I'm running out of time.

**Comment by philippefichet** [comment]
My pleasure 😉
I can close ths issue ?

**Comment by jiai** [comment]
Yes, of course. It has become a great solution to the problem! Much more than I expected.

 

Greetings,

Jessica

 
 

Gesendet: Mittwoch, 30. September 2020 um 13:08 Uhr
Von: "FICHET Philippe" <notifications@github.com>
An: "philippefichet/sonarlint4netbeans" <sonarlint4netbeans@noreply.github.com>
Cc: "jiai" <jessica-aileen@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [philippefichet/sonarlint4netbeans] Stylesheet for Sonar Rule Details Window is missing (#4)


 

My pleasure 😉
I can close ths issue ?
