### ISSUE TITLE
How can I safely remove or disable the pluguin in IDE?

### ISSUE THREAD

**Issue by thevalidator** [philippefichet/sonarlint4netbeans#59]
The problem is that it now always shows the mismatching with the rules code. I want to be able to disable the pluguin or remove it. I can't find any ways to do it in Netbeans IDE, the pluguin doesn't show separately in the installed pluguin list.

**Comment by philippefichet** [comment]
If you are referring to sonarlint4netbeans as a whole, then you need to go to your installer plugins and check the "Show details" box.

![image](https://user-images.githubusercontent.com/6843043/231203655-16a21170-bfe7-4ce4-90cc-f91dc046a68b.png)

If you just want to remove a plugin from sonarlint4netbeans (java, php or other) then this is not possible yet.
